CREATE TABLE makes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    country VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE vehicle_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    make_id BIGINT NOT NULL REFERENCES makes(id),
    name VARCHAR(100) NOT NULL,
    generation VARCHAR(100),
    body_style VARCHAR(50),
    production_start_year SMALLINT,
    production_end_year SMALLINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_vehicle_models_make_name_generation
        UNIQUE NULLS NOT DISTINCT (make_id, name, generation),
    CONSTRAINT chk_vehicle_models_production_years
        CHECK (production_end_year IS NULL
            OR production_start_year IS NULL
            OR production_end_year >= production_start_year)
);

CREATE INDEX idx_vehicle_models_make_id ON vehicle_models(make_id);
