CREATE TABLE vehicle_generations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_model_id BIGINT NOT NULL REFERENCES vehicle_models(id),
    code VARCHAR(100),
    body_style VARCHAR(50),
    production_start_year SMALLINT,
    production_end_year SMALLINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_vehicle_generations_model_code
        UNIQUE NULLS NOT DISTINCT (vehicle_model_id, code),
    CONSTRAINT chk_vehicle_generations_years
        CHECK (production_end_year IS NULL
            OR production_start_year IS NULL
            OR production_end_year >= production_start_year)
);
CREATE TABLE engines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    displacement_liters NUMERIC(5, 2),
    configuration VARCHAR(50),
    aspiration VARCHAR(50),
    fuel_type VARCHAR(50),
    rated_horsepower NUMERIC(8, 2),
    peak_horsepower_rpm NUMERIC(8, 2),
    rated_torque_nm NUMERIC(10, 3),
    peak_torque_rpm NUMERIC(8, 2),
    idle_rpm NUMERIC(8, 2) NOT NULL,
    shift_rpm NUMERIC(8, 2) NOT NULL,
    redline_rpm NUMERIC(8, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_engines_rpm_order
        CHECK (idle_rpm > 0 AND idle_rpm < shift_rpm AND shift_rpm <= redline_rpm)
);

CREATE TABLE torque_curve_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    engine_id BIGINT NOT NULL REFERENCES engines(id) ON DELETE CASCADE,
    rpm NUMERIC(8, 2) NOT NULL CHECK (rpm > 0),
    torque_nm NUMERIC(10, 3) NOT NULL CHECK (torque_nm >= 0),
    CONSTRAINT uq_torque_curve_engine_rpm UNIQUE (engine_id, rpm)
);

CREATE INDEX idx_torque_curve_points_engine_id ON torque_curve_points(engine_id);

CREATE TABLE transmissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    transmission_type VARCHAR(40) NOT NULL,
    number_of_gears SMALLINT NOT NULL CHECK (number_of_gears > 0),
    final_drive_ratio NUMERIC(10, 5) NOT NULL CHECK (final_drive_ratio > 0),
    shift_duration_seconds NUMERIC(6, 4) NOT NULL
        CHECK (shift_duration_seconds > 0 AND shift_duration_seconds <= 1),
    drivetrain_efficiency NUMERIC(6, 5) NOT NULL
        CHECK (drivetrain_efficiency > 0 AND drivetrain_efficiency <= 1),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE gear_ratios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transmission_id BIGINT NOT NULL REFERENCES transmissions(id) ON DELETE CASCADE,
    gear_number SMALLINT NOT NULL CHECK (gear_number > 0),
    ratio NUMERIC(12, 6) NOT NULL CHECK (ratio > 0),
    CONSTRAINT uq_gear_ratios_transmission_gear UNIQUE (transmission_id, gear_number)
);

CREATE INDEX idx_gear_ratios_transmission_id ON gear_ratios(transmission_id);

CREATE TABLE vehicle_trims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    generation_id BIGINT NOT NULL REFERENCES vehicle_generations(id),
    model_year SMALLINT NOT NULL CHECK (model_year BETWEEN 1886 AND 2200),
    trim_name VARCHAR(150) NOT NULL,
    engine_id BIGINT NOT NULL REFERENCES engines(id),
    transmission_id BIGINT NOT NULL REFERENCES transmissions(id),
    drivetrain VARCHAR(10) NOT NULL,
    original_msrp_usd NUMERIC(12, 2),
    tire_description VARCHAR(150),
    city_mpg NUMERIC(6, 2),
    highway_mpg NUMERIC(6, 2),
    combined_mpg NUMERIC(6, 2),
    image_url TEXT,
    is_popular BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_vehicle_trims_configuration
        UNIQUE (generation_id, model_year, trim_name, transmission_id),
    CONSTRAINT chk_vehicle_trims_drivetrain CHECK (drivetrain IN ('FWD', 'RWD', 'AWD'))
);

CREATE INDEX idx_vehicle_trims_generation_year ON vehicle_trims(generation_id, model_year);
CREATE INDEX idx_vehicle_trims_popular ON vehicle_trims(is_popular) WHERE is_popular = TRUE;

CREATE TABLE vehicle_specifications (
    vehicle_trim_id BIGINT PRIMARY KEY REFERENCES vehicle_trims(id) ON DELETE CASCADE,
    mass_kg NUMERIC(10, 3) NOT NULL CHECK (mass_kg > 0),
    static_front_weight_fraction NUMERIC(7, 6) NOT NULL
        CHECK (static_front_weight_fraction > 0 AND static_front_weight_fraction <= 1),
    wheelbase_meters NUMERIC(8, 5) NOT NULL CHECK (wheelbase_meters > 0),
    center_of_gravity_height_meters NUMERIC(8, 5) NOT NULL
        CHECK (center_of_gravity_height_meters > 0),
    wheel_radius_meters NUMERIC(8, 5) NOT NULL CHECK (wheel_radius_meters > 0),
    drag_coefficient NUMERIC(8, 5) NOT NULL CHECK (drag_coefficient > 0),
    frontal_area_square_meters NUMERIC(8, 5) NOT NULL CHECK (frontal_area_square_meters > 0),
    rolling_resistance_coefficient NUMERIC(8, 6) NOT NULL
        CHECK (rolling_resistance_coefficient > 0),
    tire_friction_coefficient NUMERIC(8, 5) NOT NULL CHECK (tire_friction_coefficient > 0),
    launch_rpm NUMERIC(8, 2) NOT NULL CHECK (launch_rpm > 0),
    launch_engagement_duration_seconds NUMERIC(6, 4) NOT NULL
        CHECK (launch_engagement_duration_seconds > 0),
    initial_torque_transfer_fraction NUMERIC(7, 6) NOT NULL
        CHECK (initial_torque_transfer_fraction > 0 AND initial_torque_transfer_fraction <= 1),
    launch_control_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE published_performance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_trim_id BIGINT NOT NULL REFERENCES vehicle_trims(id) ON DELETE CASCADE,
    zero_to_sixty_seconds NUMERIC(6, 3),
    quarter_mile_seconds NUMERIC(6, 3),
    quarter_mile_trap_speed_mph NUMERIC(7, 3),
    rollout_seconds NUMERIC(5, 3),
    source_description TEXT NOT NULL,
    UNIQUE (vehicle_trim_id, source_description)
);

CREATE TABLE vehicle_data_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_name VARCHAR(150) NOT NULL,
    source_url TEXT,
    retrieved_at TIMESTAMPTZ,
    license_notes TEXT,
    UNIQUE NULLS NOT DISTINCT (provider_name, source_url)
);

CREATE TABLE vehicle_trim_sources (
    vehicle_trim_id BIGINT NOT NULL REFERENCES vehicle_trims(id) ON DELETE CASCADE,
    source_id BIGINT NOT NULL REFERENCES vehicle_data_sources(id),
    data_status VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED',
    confidence_level VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    notes TEXT,
    PRIMARY KEY (vehicle_trim_id, source_id),
    CONSTRAINT chk_vehicle_trim_sources_status
        CHECK (data_status IN ('MEASURED', 'PUBLISHED', 'ESTIMATED', 'MANUAL')),
    CONSTRAINT chk_vehicle_trim_sources_confidence
        CHECK (confidence_level IN ('LOW', 'MEDIUM', 'HIGH'))
);
